#!/bin/bash

#    DIY webcam-driven home surveillance system
#    Copyright (C) 2015 Gabriele Musco
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
CURRENT_PATH=${PWD}

maxdiff=5 #maximum percentage of change allowed between pictures to confirm there has been no movement or people passing by
mtimer=10
fswebcam -r 640x480 --jpeg 85 1.jpg #take the first control picture with fswebcam
while [ true ]
do
	sleep $mtimer #time interval between security checks, in seconds
	fswebcam -d /dev/video0 -r 640x480 --jpeg 85 white2.jpg #take a comparison picture with fswebcam
	fswebcam -d /dev/video1 -r 640x480 --jpeg 85 blue2.jpg #take a comparison picture with fswebcam
	white_res=$(./imagecompare white2.jpg white1.jpg) #save the return value of imagecompare to make a comparison
	blue_res=$(./imagecompare blue2.jpg blue1.jpg) #save the return value of imagecompare to make a comparison
	if [ "$maxdiff" -le "$white_res" ] || [ "$maxdiff" -le "$blue_res" ]
	then
		FILENAME_WHITE=$(date +%Y-%m-%d_%H.%M.%S).png
		FILENAME_BLUE=$(date +%Y-%m-%d_%H.%M.%S).png
		mv white2.jpg $FILENAME_WHITE
		curl  \
		  -F 'recipient={"id":""}' \
		  -F 'message={"attachment":{"type":"image", "payload":{}}}' \
		  -F "filedata=@$FILENAME_WHITE;type=image/png" \
		  "https://graph.facebook.com/v2.6/me/messages?access_token="
		./dropbox-uploader/dropbox_uploader.sh upload $FILENAME_WHITE ./
		mv blue2.jpg $FILENAME_BLUE
		curl  \
		  -F 'recipient={"id":""}' \
		  -F 'message={"attachment":{"type":"image", "payload":{}}}' \
		  -F "filedata=@$FILENAME_BLUE;type=image/png" \
		  "https://graph.facebook.com/v2.6/me/messages?access_token="
		./dropbox-uploader/dropbox_uploader.sh upload $FILENAME_BLUE ./
		mtimer=3
	else
		mv white2.jpg white1.jpg
		mv blue2.jpg blue1.jpg
		mtimer=10
	fi
done

